# Generated by Django 5.0.4 on 2024-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_manager', '0003_alter_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_of_post',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
