# Generated by Django 5.0.4 on 2024-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_manager', '0005_alter_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sell_availavle',
            field=models.BooleanField(default=True),
        ),
    ]
